USER_TEXT_MAX_LENGTH = 255
CONVERSATION_LABEL_MAX_LENGTH = 32
PERSONA_MAX_LENGTH = 50
TAG_NAME_MAX_LENGTH = 50
UPLOAD_FOLDER = 'uploaded_images'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
FILE_SIZE_LIMIT = 16 * 1024 * 1024